name = "GameCapTre"
uuid = "edc02006-89b5-4de5-b03f-fcb0177a6a83"
authors = ["Perro21 <perrottamarco2011@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
