name = "Vehicle"
uuid = "e6dfaac1-45e4-40e5-9f78-12cd048089f7"
authors = ["Perro21 <perrottamarco2011@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
